spring:
    main:
        show_banner: off
    application:
        name: composite-vehicle-service
    profiles:
        active: local-dev
#logging:
#    level.org.springframework: OFF

---

spring:
    profiles: local-dev
eureka:
    instance:
        hostname: ${host.instance.name}
        nonSecurePort: ${server.port}
        leaseRenewalIntervalInSeconds: 10
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
        healthcheck:
            enabled: true
host:
    instance:
        name: localhost
server:
    port: 0

---

spring:
    profiles: prod
eureka:
    instance:
        nonSecurePort: ${server.port}
        leaseRenewalIntervalInSeconds: 10
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
        healthcheck:
            enabled: true
server:
    port: 0
