spring:
    application:
        name: simple-service
    profiles:
        active: local-dev

eureka:
    instance:
        #hostname: ${spring.application.name}
        leaseRenewalIntervalInSeconds: 10
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
        healthcheck:
            enabled: true

---

spring:
    profiles: local-dev
server:
    port: 0

---

spring:
    profiles: prod
server:
    port: 0
