spring:
    application:
        name: simple-service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.serviceInstanceId}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
        
---

spring:
    profiles: local-dev
server:
    port: 8080

---

spring:
    profiles: prod
server:
    port: 0
