spring:
    application:
        name: simple-service
    profiles:
        active: local-dev

eureka:
    instance:
        hostname: ${host.instance.name}
        nonSecurePort: 0
        leaseRenewalIntervalInSeconds: 10
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
        healthcheck:
            enabled: true

---

spring:
    profiles: local-dev
host:
    instance:
        name: localhost

---

spring:
    profiles: prod
