spring:
    application:
        name: simple-service
    profiles:
        active: local-dev

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
            instanceId: ${spring.serviceInstanceId}
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
        
---

spring:
    profiles: local-dev
server:
    port: 0

---

spring:
    profiles: prod
server:
    port: 0
