//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 09:35:41 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://entity.soap.simple.com/car", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.simple.soap.entity.car;
